<a href="https://colab.research.google.com/github/ajmd2/Jinling-Enlightenment/blob/main/base_torch/tensor_contiguous.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
a = torch.tensor([[1,2,3],
          [4,5,6],
          [7,8,9]])

print(a)
print(a.storage())
print(a.is_contiguous())

b = a.t() # 转置
print(b)
print(b.storage())
print(b.is_contiguous())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]
True
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]
False


没有开辟新的内存空间，只是转换了视角

常用的维度变换 view 和 reshape

In [ ]:
x = torch.rand(4,3)
print(x)

reshaped_x = x.view(-1,2)
print(reshaped_x)

print(x.reshape(-1,2))


tensor([[0.1464, 0.9060, 0.4334],
        [0.3459, 0.1171, 0.8813],
        [0.2563, 0.8381, 0.9691],
        [0.7802, 0.6059, 0.2662]])
tensor([[0.1464, 0.9060],
        [0.4334, 0.3459],
        [0.1171, 0.8813],
        [0.2563, 0.8381],
        [0.9691, 0.7802],
        [0.6059, 0.2662]])
tensor([[0.1464, 0.9060],
        [0.4334, 0.3459],
        [0.1171, 0.8813],
        [0.2563, 0.8381],
        [0.9691, 0.7802],
        [0.6059, 0.2662]])


In [ ]:
x.storage()

 0.14635193347930908
 0.9059754610061646
 0.433414101600647
 0.34590858221054077
 0.11710619926452637
 0.8813252449035645
 0.2563209533691406
 0.8381058573722839
 0.9691262245178223
 0.7801536321640015
 0.6059253215789795
 0.26615089178085327
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]

In [ ]:
transposed_x = x.transpose(0,1)
print(transposed_x)

tensor([[0.1464, 0.3459, 0.2563, 0.7802],
        [0.9060, 0.1171, 0.8381, 0.6059],
        [0.4334, 0.8813, 0.9691, 0.2662]])


In [ ]:
transposed_x.is_contiguous()

False

In [ ]:
transposed_x.view(-1,2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
transposed_x.reshape(-1,2)

tensor([[0.1464, 0.3459],
        [0.2563, 0.7802],
        [0.9060, 0.1171],
        [0.8381, 0.6059],
        [0.4334, 0.8813],
        [0.9691, 0.2662]])

view 不使用新的内存 只是一个新的视图，reshape会开辟新的空间

二

In [ ]:
unsqueezed_x = x.unsqueeze(0)
print(unsqueezed_x) # 在第一个维度上增加一个轴
print(unsqueezed_x.shape)

tensor([[[0.1464, 0.9060, 0.4334],
         [0.3459, 0.1171, 0.8813],
         [0.2563, 0.8381, 0.9691],
         [0.7802, 0.6059, 0.2662]]])
torch.Size([1, 4, 3])


In [ ]:
squeezed_x = unsqueezed_x.squeeze(0)
print(squeezed_x)
print(squeezed_x.shape) # squeeze只能删除维度为1的空维度

tensor([[0.1464, 0.9060, 0.4334],
        [0.3459, 0.1171, 0.8813],
        [0.2563, 0.8381, 0.9691],
        [0.7802, 0.6059, 0.2662]])
torch.Size([4, 3])
